### ISSUE TITLE
Failed to create VM (qt creator installation)

### ISSUE THREAD

**Issue by gunnarx** [Pelagicore/pelux-sde#10]
I'm failing to run this successfully (tip of master, f412fa938337165248b2b44b2b5a4f3935b1b600)

On vagrant up I get:

> default: /tmp/vagrant-shell: line 3: /opt/pelux_sdk/environment-setup*: No such file or directory

This happens during the Qt Creator installation, right after downloading the Qt Creator binary archive.

As a consequence (I guess?) the SDE installation is not finished and does not boot into a graphical environment.  Am I doing something wrong or is it confirmed broken?

Following README - running test/run.sh works, **after** making sure python=python3 and py.test = py.test-3. Using python 2 there are a bunch of errors - maybe worth documenting this).  Of course the tests reported a bunch of failures for m because of the VM was not complete.

Actually, only "check_is_ubuntu" PASSED, lol.

Let me know what I'm doing wrong...

**Comment by gunnarx** [comment]
Oh NVM, I see now, it's the SDK installation that did not happen.  

Should the Vagrant operation halt on a critical error like that?  (I know my Vagrantfiles usually don't either)

**Comment by GordanM** [comment]
@DunderRoffe  can you take a look at this please?

**Comment by gunnarx** [comment]
From what I can tell the main issue was my fault, or I will reopen again.  

I did express some ideas  here on error handling, but I think we will be able to share those ideas later if we discuss the design, so from my perspective the issue does not need to stay open.

**Comment by GordanM** [comment]
Thanks @gunnarx ! Keep us posted if you identify more problems.
