### ISSUE TITLE
SDE installation problems

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux-sde#11]
I’m trying to get Pelux SDE up and running in order to program some demo programs with Qt to RPI3.
I’ve managed to build the Pelux base platform with qtauto-neptune-dev, and after that the SDK, but I have problems when trying to get the SDE fully installed.
 
I’ve tried several times from the beginning and with default path and with changing the SDK-installation path to home folder (/home/vagrant/pelux_sdk) but every time it either stops or stucks when the Vagrantfile starts installing Qt.
 
Here is the paste from bash: 
    default:  .                                          100%  129K=9m54s
    default:
    default: 2018-03-27 14:12:19 (207 KB/s) - ‘/tmp/qt-creator-installer-8O3sr0yT.run’ saved [125963924/125963924]
    default: QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Empty filename passed to function
    default: Empty filename passed to function
    default: Empty filename passed to function
    default: Empty filename passed to function
    default: /usr/bin/env: ‘python3\r’: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 
I’d really appreciate your help.

**Comment by GordanM** [comment]
Resolution found. 

> default: /usr/bin/env: ‘python3\r’: No such file or directory

It seems like the carriage return `\r` was not interpreted properly. The reporter of the bug was using Windows natively while cloning the repository with Git Bash. The line breaks were converted to Winows CRLF.

> This was the problem. I'm running Windows and cloning the repository with Git Bash changed the line endings to Windows CRLF. I double-checked and this is the cause for the change.
> I used "Edit -> EOL Conversion -> Unix (LF)" in Notepad++ to convert the scripts back to Unix line endings and now I have the SDE up and running.
