### ISSUE TITLE
SDE installation issue default: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by Shazter** [Pelagicore/pelux-sde#29]
Installed Vagrant and VM last version on Host PC.

Instead of building the SDK installer I downloaded here [Link](https://pelux.io/artifacts/pelux/3.0/binaries/intel/pelux-glibc-x86_64-core-image-pelux-qtauto-neptune-dev-corei7-64-toolchain-3.0.sh)

Cloned the plexu-sde master rep., copied the sdk installer into the root and then started as described installation with `SDK_FILE_NAME=pelux-glibc-x86_64-core-image-pelux-qtauto-neptune-dev-corei7-64-toolchain-3.0.sh vagrant up`

The VM starts up and the host pc terminal shows installation process, after some time ends with 

```
/communicator.rb:257:in `execute': The SSH command responded with a non-zero exit status. Vagrant (Vagrant::Errors::VagrantError)
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
When I check terminal output then I see 

```
default:  update-manager-core
default:  update-notifier-common
default:  update-notifier
default:  ubuntu-desktop
default:  update-manager
default:  ubuntu-gnome-desktop
default: E
default: : 
default: Sub-process /usr/bin/dpkg returned an error code (1)

Any guidance if I'm doing something wrong? Or how to find root cause?
```

**Comment by sashko** [comment]
Could you please provide us with the full log?

**Comment by sashko** [comment]
Turns out, the image provider has updated the Ubuntu image and it broke our installation scripts. I've made some changes to make sure this doesn't happen in the future.

Thank you for reporting the issue, @Shazter!

**Comment by Shazter** [comment]
Is it fixed in the master branch? If yes then I will check and give feedback, if we Bug can be closed.

**Comment by sashko** [comment]
> Is it fixed in the master branch? If yes then I will check and give feedback, if we Bug can be closed.

Just pushed the fix to `master`.
